### PR TITLE
Embed videos in markdown

### PR DESCRIPTION
**Pull request by wale-bant**
Instead of having just links to YouTube videos, the videos are embedded in the readme itself with a preview so that user doesn't have to navigate to YouTube to watch them.

### CODE REVIEW

**Comment by hjaintech** [comment]
@wale-bant Please check if you can make these videos run here only. Currently on clicking the preview, it is navigating to youtube.

**Comment by wale-bant** [comment]
It's not possible to embed videos directly, but you can put an image which links to a YouTube video:

**Comment by hjaintech** [comment]
@wale-bant  Cool. Awesome stuff. Merging it.

**Comment by hjaintech** [comment]
This PR fixes #4

**Pull request merged**
